import enum
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base
from app.models.mixins import TimestampMixin


class AnswerSource(str, enum.Enum):
    user = "user"  # authored/approved by the human - always trusted
    llm = "llm"  # generated by the agent - a suggestion until approved


class AnswerBankEntry(Base, TimestampMixin):
    """A remembered answer to a free-text application question, so recurring
    questions are filled deterministically instead of hitting the LLM every
    time. Only `approved` entries are reused by the agent (review-gated); LLM
    answers land here as suggestions (`approved=False`) for the human to vet."""

    __tablename__ = "answer_bank"

    id: Mapped[int] = mapped_column(primary_key=True)
    # Normalized question text (lowercase, punctuation-stripped) - the match
    # key. Unique so there is one canonical entry per question.
    question_norm: Mapped[str] = mapped_column(String(512), nullable=False, unique=True, index=True)
    question_raw: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[AnswerSource] = mapped_column(
        Enum(AnswerSource, native_enum=False), nullable=False, default=AnswerSource.user
    )
    approved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    times_used: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
