"""initial schema

Revision ID: 46f5506dd4da
Revises: 
Create Date: 2026-07-01 19:28:36.519166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46f5506dd4da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'queued', 'in_progress', 'ready_to_submit', 'submitted', 'oa', 'interview', 'offer', 'rejected', 'withdrawn', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('resume_version_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('careers_url', sa.String(length=1024), nullable=True),
    sa.Column('ats_type', sa.Enum('greenhouse', 'lever', 'ashby', 'workday', 'other', 'unknown', name='atstype', native_enum=False), nullable=False),
    sa.Column('ats_board_id', sa.String(length=255), nullable=True),
    sa.Column('is_target', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_family', sa.Enum('swe', 'data', 'cloud_infra', 'ml', 'other', name='jobfamily', native_enum=False), nullable=False),
    sa.Column('latex_source', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('is_base_template', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.Enum('greenhouse', 'lever', 'ashby', 'github_repo', 'manual', name='jobsource', native_enum=False), nullable=False),
    sa.Column('role_type', sa.Enum('internship', 'full_time', name='roletype', native_enum=False), nullable=False),
    sa.Column('job_family', sa.Enum('swe', 'data', 'cloud_infra', 'ml', 'other', name='jobfamily', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_jobs_dedup_hash'), 'jobs', ['dedup_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_dedup_hash'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('resume_versions')
    op.drop_table('cover_letters')
    op.drop_table('companies')
    op.drop_table('applications')
    # ### end Alembic commands ###
