"""add jd_keywords to job

Revision ID: 6d114ed60f6e
Revises: 46f5506dd4da
Create Date: 2026-07-01 23:10:27.391264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d114ed60f6e'
down_revision: Union[str, None] = '46f5506dd4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('jd_keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'jd_keywords')
    # ### end Alembic commands ###
